version: '3.4'

services:
    nginx:
        image: nginx:latest
        depends_on:
            - php
        ports:
            - "80:80"
        volumes:
            - ${PROJECT_PATH}:/app
            - ./config/nginx/conf.d:/etc/nginx/conf.d/
            - ./volumes/nginx/logs:/var/log/nginx/
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: ./php.dockerfile
        container_name: php-7.4
        depends_on:
            - postgres
        volumes:
            - ${PROJECT_PATH}:/app
        environment:
            TZ: ${WORKSPACE_TIMEZONE}
        ports:
            - "${PHP_PORT}:9000"
        networks:
            - app-network

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            TZ: ${WORKSPACE_TIMEZONE}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./volumes/db/data:/var/lib/postgesql/data
            - ./volumes/db/dump:/dump
        networks:
            - app-network

networks:
    app-network:
        driver: bridge