version: '3.4'

services:
    nginx:
        image: nginx:latest
        depends_on:
            - php
        ports:
            - "80:80"
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: ./php.dockerfile
        depends_on:
            - postgres
        volumes:
            - ${PROJECT_PATH}:/app
        networks:
            - app-network

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - "5432:5432"
        volumes:
            - ./volumes/db:/var/lib/postgesql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge